import { useEffect, useState } from 'react'
import heroBanner from '../../assets/images/hero-banner.jpg'
import SectionHeading from '../../components/common/SectionHeading'
import AdBoard from '../../components/common/AdBoard'
import { siteConfig } from '../../constants/site'
import { getFacebookPosts, type FacebookPost } from '../../api/facebook'

type SiteSettings = { name: string; description: string; phone: string; whatsapp: string; address: string; hours: string; googleMaps: string }
function formatDate(value: string) { try { return new Intl.DateTimeFormat('ar-DZ', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) } catch { return value } }
function normalizeUrl(value: string, fallback: string) { if (!value) return fallback; const markdownMatch = value.match(/^\[([^\]]+)\]\((https?:\/\/[^)]+)\)$/); if (markdownMatch) return markdownMatch[2]; return value }
type FeaturedPost = { id: string; message?: string; createdTime?: string; permalinkUrl?: string; imageUrl?: string; videoUrl?: string }

function HomePage() {
  const [siteSettings, setSiteSettings] = useState<SiteSettings>({ name: siteConfig.name || '', description: siteConfig.description || '', phone: '', whatsapp: siteConfig.whatsapp || '', address: '', hours: '', googleMaps: siteConfig.mapsUrl || '' })
  const [posts, setPosts] = useState<FacebookPost[]>([])
  const [featuredPosts, setFeaturedPosts] = useState<FeaturedPost[]>([])
  const [loading, setLoading] = useState(true)
  const [featuredLoading, setFeaturedLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => { let isMounted = true; async function loadSettings() { try { const response = await fetch('/api/settings'); if (!response.ok) throw new Error('Failed to load settings'); const data = await response.json(); if (isMounted && data?.site) setSiteSettings((current) => ({ ...current, ...data.site })) } catch (error) { console.error('Failed to load site settings:', error) } } void loadSettings(); return () => { isMounted = false } }, [])
  useEffect(() => { let isMounted = true; async function loadPosts() { try { const data = await getFacebookPosts(4); if (isMounted) { setPosts(data); setError(null) } } catch (err) { console.error(err); if (isMounted) setError('تعذر تحميل المنشورات الآن') } finally { if (isMounted) setLoading(false) } } void loadPosts(); return () => { isMounted = false } }, [])
  useEffect(() => { let isMounted = true; async function loadFeaturedPosts() { try { const response = await fetch('/api/admin/featured-posts', { cache: 'no-store' }); if (!response.ok) throw new Error('Failed to load featured posts'); const data = await response.json(); if (isMounted) setFeaturedPosts(Array.isArray(data?.posts) ? data.posts : []) } catch (error) { console.error('Failed to load featured posts:', error); if (isMounted) setFeaturedPosts([]) } finally { if (isMounted) setFeaturedLoading(false) } } void loadFeaturedPosts(); return () => { isMounted = false } }, [])
  const mapsUrl = normalizeUrl(siteSettings.googleMaps, siteConfig.mapsUrl)

  return (
    <div className="relative min-h-screen overflow-hidden bg-white pb-12">
      <div aria-hidden="true" className="pointer-events-none fixed inset-0 z-0 bg-cover bg-center bg-fixed" style={{ backgroundImage: `url(${heroBanner})` }}><div className="absolute inset-0 bg-white/90 backdrop-blur-[1px]" /></div>
      <div className="relative z-10">
        <section id="home" className="border-b border-rose-100/60 bg-transparent"><div className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12"><div className="relative overflow-hidden rounded-[2.5rem] border border-white/70 bg-white/45 p-6 shadow-xl shadow-slate-300/20 backdrop-blur-sm sm:p-10"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex rounded-full bg-white/80 px-4 py-1.5 text-xs font-bold text-rose-600 shadow-sm">كل شيء بالمعقول</span><h1 className="mt-4 text-3xl font-black leading-tight text-slate-900 sm:text-5xl">كل ما تحتاجه... بالمعقول</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-700 sm:text-base">اكتشف جديدنا وتابع أحدث المنشورات والعروض الخاصة بالمحل.</p><a href="#featured" className="mt-6 inline-flex rounded-full bg-rose-600 px-6 py-3 text-sm font-bold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-rose-700">اكتشف جديدنا</a></div></div></div></section>
        <section id="featured" className="mx-auto w-full max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-6 xl:grid-cols-[340px_minmax(0,1fr)]">
          <article className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-lg shadow-slate-300/20 backdrop-blur-sm sm:p-8"><SectionHeading eyebrow="جديدنا" title="" description="" />{loading ? <div className="mt-8 rounded-[1.5rem] border border-slate-200 bg-slate-50/90 p-8 text-center text-slate-500">جارٍ تحميل المنشورات...</div> : error ? <div className="mt-8 rounded-[1.5rem] border border-rose-200 bg-rose-50/90 p-6 text-center text-rose-700">{error}</div> : posts.length === 0 ? <div className="mt-8 rounded-[1.5rem] border border-slate-200 bg-slate-50/90 p-8 text-center text-slate-500">لا توجد منشورات متاحة حاليًا.</div> : <div className="mt-8 space-y-4">{posts.map((post) => <a key={post.id} href={post.permalinkUrl} target="_blank" rel="noreferrer" className="flex gap-4 rounded-[1.5rem] border border-slate-100 bg-white/80 p-3 transition duration-300 hover:-translate-y-0.5 hover:border-rose-200 hover:bg-white hover:shadow-sm"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-slate-100">{post.videoUrl ? <video src={post.videoUrl} poster={post.imageUrl || undefined} muted playsInline preload="metadata" className="h-full w-full object-cover" /> : post.imageUrl ? <img src={post.imageUrl} alt={post.message} className="h-full w-full object-cover" /> : <div className="h-full w-full bg-gradient-to-br from-rose-100 via-white to-fuchsia-100" />}</div><div className="min-w-0 flex-1 text-right"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-white px-3 py-1 text-[11px] font-semibold tracking-[0.18em] text-rose-600 uppercase">Facebook</span><span className="text-[11px] text-slate-500">{formatDate(post.createdTime)}</span></div><p className="mt-2 text-[13px] leading-5 text-slate-600" style={{ display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>{post.message}</p></div></a>)}</div>}</article>
          <article className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-lg shadow-slate-300/20 backdrop-blur-sm sm:p-8"><SectionHeading eyebrow="المنشورات المميزة" title="" description="" />{featuredLoading ? <div className="mt-8 rounded-[1.5rem] border border-slate-200 bg-slate-50/90 p-8 text-center text-slate-500">جارٍ تحميل المنشورات المميزة...</div> : featuredPosts.length === 0 ? <div className="mt-8 rounded-[1.5rem] border border-dashed border-slate-200 bg-slate-50/90 p-8 text-center text-slate-500">لا توجد منشورات مميزة حاليًا.</div> : <div className="mt-8 grid gap-5 lg:grid-cols-3">{featuredPosts.map((post) => <article key={post.id} className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-slate-50/90 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg">{post.videoUrl ? <video src={post.videoUrl} poster={post.imageUrl || undefined} controls playsInline preload="metadata" className="h-48 w-full bg-black object-cover" /> : post.imageUrl ? <img src={post.imageUrl} alt="" className="h-48 w-full object-cover" loading="lazy" /> : null}{post.videoUrl ? null : <div className="p-5"><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold tracking-[0.2em] text-rose-500 uppercase">Facebook</span><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-rose-700 ring-1 ring-rose-100">مثبت</span></div><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{post.message || 'منشور بدون نص'}</p><div className="mt-5 flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{formatDate(post.createdTime || '')}</span>{post.permalinkUrl ? <a href={post.permalinkUrl} target="_blank" rel="noreferrer" className="text-sm font-semibold text-rose-700 transition hover:text-rose-800">عرض المنشور ↗</a> : null}</div></div>}{post.videoUrl && post.permalinkUrl ? <div className="p-2 text-center"><a href={post.permalinkUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-rose-700 hover:text-rose-800">عرض المنشور ↗</a></div> : null}</article>)}</div>}</article>
        </div></section>
        <section id="latest" className="bg-transparent py-14"><div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-6 xl:grid-cols-[1.15fr_1.25fr_1fr]">
          <AdBoard />
          <article id="location" className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-lg shadow-slate-300/20 backdrop-blur-sm sm:p-8"><SectionHeading eyebrow="موقعنا" title="" description="" /><div className="mt-6"><div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-slate-50"><iframe title="خريطة الوصول إلى المحل" src={`https://www.google.com/maps?q=${encodeURIComponent(siteSettings.address)}&output=embed`} className="h-64 w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div className="p-4 text-right"><a href={mapsUrl} target="_blank" rel="noreferrer" className="mt-0 inline-flex rounded-full bg-rose-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-rose-700">فتح الاتجاهات</a></div></div></div></article>
          <article className="rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-lg shadow-slate-300/20 backdrop-blur-sm sm:p-8"><SectionHeading eyebrow="نبذة عن المحل" title="" description="" /><div className="mt-6 text-right"><p className="whitespace-pre-line text-sm leading-7 text-slate-600">{siteSettings.description}</p></div></article>
        </div></div></section>
      </div>
    </div>
  )
}

export default HomePage
